hand:
  graphical:
      guzheng:
          img4: https://statics.pnlyy.com/mini_guarder_ic_guzheng4@2x.png
          img3: https://statics.pnlyy.com/mini_guarder_ic_guzheng3@2x.png
          img2: https://statics.pnlyy.com/mini_guarder_ic_guzheng2@2x.png
          img1: https://statics.pnlyy.com/mini_guarder_ic_guzheng@2x.png
